[tox]
requires = tox-uv
envlist = lint,py{310,311,312,313,314}

[testenv]
runner = uv-venv-lock-runner
dependency_groups = tests
commands =
    pytest --cov=flask_googlestorage --cov-report=xml {posargs}

[testenv:lint]
runner = uv-venv-lock-runner
dependency_groups = lint
skip_install = True
commands =
    ruff check flask_googlestorage tests
    ruff format --check flask_googlestorage tests
