[tox]
envlist = lint,py{310,311,312,313,314}

[testenv]
deps = 
    -rtest-requirements.txt
commands =
    pytest --cov=flask_googlestorage --cov-report=xml {posargs}

[testenv:lint]
deps = -rlint-requirements.txt
skip_install = True
commands =
    flake8 flask_googlestorage tests --max-line-length=100 --max-complexity 10