name: Python package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      - name: Run tox
        run: uv run tox
      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v7"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
